name: Daily Repository Update

on:
  schedule:
    - cron: '30 02 * * *'  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure Git (23f2001390@ds.study.iitm.ac.in)
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "23f2001390@ds.study.iitm.ac.in"
      
      - name: Create daily update
        run: |
          # Create updates directory if it doesn't exist
          mkdir -p updates
          
          # Generate timestamp file with additional information
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S UTC')
          {
            echo "Repository Update Log"
            echo "===================="
            echo "Last Updated: $TIMESTAMP"
            echo "Workflow Run ID: $GITHUB_RUN_ID"
            echo "Workflow Run Number: $GITHUB_RUN_NUMBER"
          } > "updates/update_${GITHUB_RUN_NUMBER}.log"
      
      - name: Commit and push changes
        run: |
          git add updates/
          git commit -m "Daily repository update - $GITHUB_RUN_NUMBER [$(date '+%Y-%m-%d')]" || exit 0
          git push
